# Generated by Django 6.0.3 on 2026-03-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='ssh_host',
            field=models.CharField(blank=True, help_text='e.g. openport.io', max_length=255),
        ),
        migrations.AddField(
            model_name='server',
            name='ssh_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='server',
            name='ssh_port',
            field=models.IntegerField(blank=True, default=22),
        ),
        migrations.AddField(
            model_name='server',
            name='ssh_user',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
